services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: dev-pokedex-backend
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - ./compose/backend.env
    volumes:
      - ./backend:/backend
